[package]
name = "tui-mutagen-solver"
version = "0.1.0"
authors = ["Ougers <vlado.miladinovic1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ordered-float = "4.2.0"
priority-queue = "2.0.2"
ratatui = "0.26.0"
